In [1]:
import firebase_admin
from firebase_admin import credentials, firestore
import pandas as pd

In [2]:

df=pd.read_csv("orginal_sales_data_edit.csv",encoding="utf-8",header=0,delimiter=',')

In [3]:
df.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,PAYMENTFULLNAME
0,10107,30,95.70,2,2871.00,2/24/2003,Shipped,1,2,2003,...,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small,Yu Kwai
1,10121,34,81.35,5,2765.90,5/7/2003,Shipped,2,5,2003,...,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small,Henriot Paul
2,10134,41,94.74,2,3884.34,7/1/2003,Shipped,3,7,2003,...,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium,DaCunha Daniel
3,10145,45,83.26,6,3746.70,8/25/2003,Shipped,3,8,2003,...,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium,Young Julie
4,10159,49,100.00,14,5205.27,10/10/2003,Shipped,4,10,2003,...,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium,Brown Julie

In [4]:
cred=credentials.Certificate("./iuh-20068371-69927-firebase-adminsdk-x1k69-8e20e03d7e.json")
app=firebase_admin.initialize_app(cred)

In [5]:
dbFireStore=firestore.client()

In [6]:
for item in df.to_dict(orient='records'):
    doc_ref = dbFireStore.collection("tbl-20068371").document()
    doc_ref.set(item)

In [7]:
queryResults = list(dbFireStore.collection(u'tbl-20068371').stream())
listQueryResult = list(map(lambda x : x.to_dict(), queryResults))
df = pd.DataFrame(listQueryResult)
df

,TERRITORY,ORDERLINENUMBER,SUBCATEGORY,CITY,STATUS,ADDRESSLINE1,ADDRESSLINE2,YEAR_ID,CONTACTLASTNAME,COUNTRY,...,ORDERNUMBER,PHONE,DEALSIZE,MONTH_ID,PAYMENTFULLNAME,STATE,MSRP,CATEGORY,PRODUCTCODE,POSTALCODE
0,NaN,10,Bookshelf,Nashua,Shipped,2304 Long Airport Avenue,NaN,2004,Young,USA,...,10322,6035558647,Small,11,Young Valarie,NH,116,Furniture,S18_1097,62005
1,EMEA,1,Ruler,Cowes,Shipped,Garden House Crowther Way,NaN,2004,Bennett,UK,...,10316,(198) 555-8888,Small,11,Bennett Helen,Isle of Wight,109,Office Supplies,S24_1785,PO31 7PJ
2,NaN,1,Pen,Vancouver,Shipped,1900 Oak St.,NaN,2004,Tannamuri,Canada,...,10313,(604) 555-3392,Small,10,Tannamuri Yoshi,BC,54,Office Supplies,S32_2509,V3F 2K1
3,NaN,7,Eraser,NYC,Shipped,897 Long Airport Avenue,NaN,2004,Yu,USA,...,10329,2125557818,Small,11,Yu Kwai,NY,112,Office Supplies,S24_1578,10022
4,NaN,11,Pen,Pasadena,Shipped,78934 Hillside Dr.,NaN,2003,Young,USA,...,10145,6265557265,Medium,8,Young Julie,CA,76,Office Supplies,S24_2000,90003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,EMEA,2,Bookshelf,Gensve,Shipped,Grenzacherweg 237,NaN,2004,Holz,Switzerland,...,10287,0897-034555,Medium,8,Holz Michael,NaN,141,Furniture,S18_3685,1203
2819,EMEA,4,Eraser,Bergamo,Shipped,Via Ludovico il Moro 22,NaN,2004,Rovelli,Italy,...,10328,035-640555,Small,11,Rovelli Giovanni,NaN,72,Office Supplies,S24_4278,24100
2820,NaN,4,Lamp,San Francisco,Shipped,5557 North Pendale Street,NaN,2004,Murphy,USA,...,10333,6505555787,Small,11,Murphy Julie,CA,64,Office Supplies,S32_3522,NaN
2821,EMEA,6,Table,Paris,Shipped,"265, boulevard Charonne",NaN,2004,Bertrand,France,...,10336,(1) 42.34.2555,Large,11,Bertrand Marie,NaN,163,Furniture,S18_2238,75012
2822,NaN,7,Bookshelf,San Rafael,Shipped,5677 Strong St.,NaN,2005,Nelson,USA,...,10390,4155551450,Small,3,Nelson Valarie,CA,168,Furniture,S18_2795,97562

In [8]:
queryResults1 = list(dbFireStore.collection(u'tbl-20068371').where(u'COUNTRY', u'==', 'USA').stream())
listQueryResult1 = list(map(lambda x : x.to_dict(), queryResults1))
df1 = pd.DataFrame(listQueryResult1)
df1

,TERRITORY,SUBCATEGORY,ORDERLINENUMBER,CITY,STATUS,ADDRESSLINE1,ADDRESSLINE2,YEAR_ID,CONTACTLASTNAME,COUNTRY,...,ORDERNUMBER,PHONE,DEALSIZE,MONTH_ID,PAYMENTFULLNAME,STATE,MSRP,CATEGORY,PRODUCTCODE,POSTALCODE
0,NaN,Bookshelf,10,Nashua,Shipped,2304 Long Airport Avenue,NaN,2004,Young,USA,...,10322,6035558647,Small,11,Young Valarie,NH,116,Furniture,S18_1097,62005
1,NaN,Eraser,7,NYC,Shipped,897 Long Airport Avenue,NaN,2004,Yu,USA,...,10329,2125557818,Small,11,Yu Kwai,NY,112,Office Supplies,S24_1578,10022
2,NaN,Pen,11,Pasadena,Shipped,78934 Hillside Dr.,NaN,2003,Young,USA,...,10145,6265557265,Medium,8,Young Julie,CA,76,Office Supplies,S24_2000,90003
3,NaN,Laptop,7,Boston,On Hold,8616 Spinnaker Dr.,NaN,2005,Yoshido,USA,...,10414,6175559555,Medium,5,Yoshido Juri,MA,100,Technology,S700_3505,51003
4,NaN,Laptop,4,New Bedford,Shipped,4575 Hillside Dr.,NaN,2003,Tam,USA,...,10185,5085559555,Medium,11,Tam WingC,MA,100,Technology,S700_3505,50553
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,NaN,Bookshelf,4,Las Vegas,Shipped,8489 Strong St.,NaN,2004,King,USA,...,10278,7025551838,Medium,8,King Sue,NV,141,Furniture,S18_3685,83030
1000,NaN,Bookshelf,8,Bridgewater,Shipped,25593 South Bay Ln.,NaN,2003,King,USA,...,10172,2035552570,Medium,11,King Julie,CT,141,Furniture,S18_3685,97562
1001,NaN,Ruler,9,White Plains,Shipped,3758 North Pendale Street,NaN,2004,Frick,USA,...,10308,9145554562,Medium,10,Frick Steve,NY,109,Office Supplies,S24_1785,24067
1002,NaN,Lamp,4,San Francisco,Shipped,5557 North Pendale Street,NaN,2004,Murphy,USA,...,10333,6505555787,Small,11,Murphy Julie,CA,64,Office Supplies,S32_3522,NaN
1003,NaN,Bookshelf,7,San Rafael,Shipped,5677 Strong St.,NaN,2005,Nelson,USA,...,10390,4155551450,Small,3,Nelson Valarie,CA,168,Furniture,S18_2795,97562